--CREATE TABLE users (
--    user_id BIGSERIAL PRIMARY KEY,
--
--    username VARCHAR(100) NOT NULL UNIQUE,
--    email VARCHAR(255) NOT NULL UNIQUE,
--    password_hash VARCHAR(255),
--
--    first_name VARCHAR(100),
--    middle_name VARCHAR(100),
--    last_name VARCHAR(100),
--    full_name VARCHAR(255),
--
--    phone_number VARCHAR(50),
--    country_code VARCHAR(10),
--
--    hs_uuid UUID,
--    hs_id INTEGER,
--
--    role_id BIGINT NOT NULL,
--    CONSTRAINT fk_user_role
--        FOREIGN KEY (role_id)
--        REFERENCES roles(role_id)
--        ON DELETE RESTRICT,
--
--    entity_id BIGINT,
--    CONSTRAINT fk_user_entity
--        FOREIGN KEY (entity_id)
--        REFERENCES organizations(id)
--        ON DELETE SET NULL,
--
--    site_id UUID,
--    CONSTRAINT fk_user_site
--        FOREIGN KEY (site_id)
--        REFERENCES sites(id)
--        ON DELETE SET NULL,
--
--    classroom_id UUID,
--    CONSTRAINT fk_user_classroom
--        FOREIGN KEY (classroom_id)
--        REFERENCES classrooms(id)
--        ON DELETE SET NULL,
--
--    last_login_time TIMESTAMP,
--
--    is_active BOOLEAN DEFAULT TRUE,
--    is_password_updated BOOLEAN DEFAULT FALSE
--);

CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password_hash VARCHAR(255),
   first_name VARCHAR(255),
   middle_name VARCHAR(255),
   last_name VARCHAR(255),
   full_name VARCHAR(255),
   phone_number VARCHAR(255),
   country_code VARCHAR(255),
   hs_uuid UUID,
   hs_id INTEGER,
   role_id BIGINT NOT NULL,
   entity_id BIGINT,
   site_id UUID,
   classroom_id UUID,
   last_login_time TIMESTAMP WITHOUT TIME ZONE,
   is_active BOOLEAN,
   is_password_updated BOOLEAN,
   CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_CLASSROOM FOREIGN KEY (classroom_id) REFERENCES classrooms (id);

ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_ENTITY FOREIGN KEY (entity_id) REFERENCES organizations (id);

ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE users ADD CONSTRAINT FK_USERS_ON_SITE FOREIGN KEY (site_id) REFERENCES sites (id);