CREATE TABLE service_centers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_by VARCHAR(255),
   created_date TIMESTAMP WITHOUT TIME ZONE,
   last_modified_by VARCHAR(255),
   last_modified_date TIMESTAMP WITHOUT TIME ZONE,
   hs_id INTEGER,
   service_name VARCHAR(255) NOT NULL,
   no_of_licenses INTEGER,
   is_deleted BOOLEAN,
   entity_id BIGINT NOT NULL,
   subscription_type VARCHAR(255),
   subscription_start_date TIMESTAMP WITHOUT TIME ZONE,
   subscription_expired_date TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_service_centers PRIMARY KEY (id)
);

ALTER TABLE service_centers ADD CONSTRAINT FK_SERVICE_CENTERS_ON_ENTITY FOREIGN KEY (entity_id) REFERENCES organizations (id);